import java.awt.Graphics2D;

/**
 * Provides support for the various kinds of custom curves generated by Paint and Graphics
 * Types of curves supported:
 * <ul>
 *     <li>Polygon</li>
 *     <li>Triangle groups</li>
 *     <li>Quad groups</li>
 *     <li>open curves</li>
 *     <li>closed curves</li>
 * </ul>
 */
class Curve
{
    public int t;
    Polygon[] p;
    int c = 0;

    /**
     * Constructor for the Curve class.
     * @param type the type of curve to be generated
     */
    public Curve( int type )
    {
        t = type;
        if ( type == 3 )
        {
            Polygon po = new Polygon();
            po.noFill = true;
            p = add( po );
        }
        else if ( type == 4 )
        {
            Polygon po = new Polygon();
            po.strict = true;
            p = add( po );
        }
        else
        {
            p = add( new Polygon() );
        }
    }

    /**
     * Adds a new Polygon to the array of Polygons.
     * @param poly the Polygon to be added
     * @return  the array of Polygons with the new Polygon added
     */
    public Polygon[] add( Polygon poly )
    {
        Polygon[] temp = new Polygon[p.length + 1];
        System.arraycopy( p, 0, temp, 0, p.length );
        temp[p.length] = poly;
        return temp;
    }

    /**
     * Adds a new point to the current Polygon.
     * @param a the point to be added
     */
    public void addVertex( Vertex a )
    {
        if ( this.t == 1 )
        {
            if ( p[c].vert.length == 3 )
            {
                c += 1;
                p = add( new Polygon() );
                p[c].addVertex( a );
            }
            else
            {
                p[c].addVertex( a );
            }
        }
        else if ( this.t == 2 )
        {
            if ( p[c].vert.length == 4 )
            {
                c += 1;
                p = add( new Polygon() );
                p[c].addVertex( a );
            }
            else
            {
                p[c].addVertex( a );
            }
        }
        else
        {
            p[c].addVertex( a );
        }

    }

    /**
     * Draws the curve.
     * @param g the Graphics2D context
     * @param pa The painting instructions for the curve
     */
    public void draw( Graphics2D g, Painting_instr pa )
    {
        for ( Polygon po : p )
        {
            po.draw( g, pa );
        }
    }
}
